services:
  mysql:
    image: mysql:8
    environment:

      MYSQL_DATABASE: ourkanban

      MYSQL_USER: ourkanban

      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 10
      


  backend:
    build: .
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ourkanban
      JWT_SECRET: ${JWT_SECRET}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_APP_PASSWORD: ${MAIL_APP_PASSWORD}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
    expose:
      - "8080"
    restart: unless-stopped
  
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    depends_on:
      - backend
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      - ./nginx/ssl:/etc/nginx/ssl:ro
  
  cloudflare-ddns:
    image: favonia/cloudflare-ddns:latest
    container_name: cloudflare-ddns
    restart: unless-stopped
    network_mode: host
    environment:
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
      - DOMAINS=twinchainstudiostesting.es,www.twinchainstudiostesting.es
      - PROXIED=true
  cloudflare-ddns-ssh:
    image: favonia/cloudflare-ddns:latest
    container_name: cloudflare-ddns-ssh
    restart: unless-stopped
    network_mode: host
    environment:
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
      - DOMAINS=ssh.twinchainstudiostesting.es
      - PROXIED=false


volumes:
  mysql_data: